//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace futbolApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futbolcular
    {
        public int FormaNo { get; set; }
        public string FutbolcuAdi { get; set; }
        public string FutbolcuSoyadi { get; set; }
        public string Telefonu { get; set; }
        public string Ulkesi { get; set; }
    }
}
