//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace futbolApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakemler
    {
        public int HakemId { get; set; }
        public string HakemAdi { get; set; }
        public string HakemTelefon { get; set; }
        public Nullable<int> TecrubeYili { get; set; }
        public Nullable<int> HakemYas { get; set; }
    }
}
