//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace futbolApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maclar
    {
        public int MacId { get; set; }
        public string MacSehir { get; set; }
        public Nullable<int> TaraftarSayisi { get; set; }
        public Nullable<decimal> GirisUcret { get; set; }
        public Nullable<System.DateTime> MacTarih { get; set; }
    }
}
